[package]
name = "btx"
version = "0.1.0"
authors = ["xuhua <cxuhua@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
leveldb = "0.8.6"
env_logger = "0.8.2"
ripemd160 = "0.9.1"
bech32 = "0.7.2"
sha2 = "0.8.2"
hex = "0.4.2"
bytes = "0.5.6"
tempdir = "0.3.7"
rsa = "0.3.0"
rand = "0.7.3"
enum_derive = "0.1.7"
custom_derive = "0.1.7"
secp256k1 = { version = "0.20.0", features = [ "rand-std" ] }